Repository nextcloud/privacy, pull requests merged in 2019-03, with the labels that each got.

#58 Capitalize User Data Manifesto
  templates/user-data-manifesto.php
Labels: bug

#59 Fix the sections order, show the map last
  lib/Settings/WhereIsYourDataSettings.php
  lib/Settings/WhoHasAccessSettings.php
Labels: enhancement

#62 Fix CI
  .travis.yml
  Makefile
  composer.json
  composer.lock
  js/script.js
  js/script.js.map
Labels: bug

#61 Add composer.lock file
  composer.lock
Labels: enhancement

#60 Update build assets and add gitattribute file
  .gitattributes
Labels: bug

#67 Fixes for default enable and typo
  appinfo/info.xml
  templates/who-has-access.php
Labels: 4. to release

#75 Add a privacy policy link if it's set
  lib/Settings/WhoHasAccessSettings.php
  templates/who-has-access.php
Labels: 3. to review, enhancement

#74 Fix JS build break
  js/script.js
  js/script.js.map
  package-lock.json
  package.json
Labels: 3. to review, bug, technical debt
