Repository nextcloud/privacy, pull requests merged in 2020-04, with the labels that each got.

#387 Move to Github Actions
  .github/workflows/dependabot-approve.yml
  .github/workflows/lint.yml
  .gitignore
  .php_cs.dist
  .travis.yml
  appinfo/routes.php
  composer.json
  composer.lock
  lib/Controller/PersonalController.php
  lib/Settings/MissionSettings.php
  lib/Settings/PrivacySection.php
  lib/Settings/UserDataManifestoSettings.php
  lib/Settings/WhereIsYourDataSettings.php
  lib/Settings/WhoHasAccessSettings.php
  tests/Integration/AppTest.php
  tests/Unit/Controller/PageControllerTest.php
  tests/bootstrap.php
Labels: 3. to review

#277 Add missing regions from ISO 3166
  src/components/Location.vue
  src/nameProvider.js
Labels: 3. to review, enhancement

#389 Correction of the description
  src/nameProvider.js
Labels: 3. to review, design
