Repository nextcloud/privacy, pull requests merged in 2022-01, with the labels that each got.

#662 Update npm and node engines versions
  package.json
Labels: dependencies

#670 Bump dependencies and configs
  .eslintrc.js
  .github/workflows/lint-stylelint.yml
  .stylelintrc.js
  js/privacy-main.js
  js/privacy-main.js.LICENSE.txt
  js/privacy-main.js.map
  lib/Settings/MissionSettings.php
  package-lock.json
  package.json
  stylelint.config.js
  templates/mission.php
Labels: enhancement, dependencies, 3. to review

#674 Fix label of account name and hide parts with subscription
  lib/Settings/MissionSettings.php
  lib/Settings/UserDataManifestoSettings.php
  templates/mission.php
Labels: bug, 3. to review, backport-request

#683 Create block-merge-freeze.yml
  .github/workflows/block-merge-freeze.yml
Labels: backport-request

#690 Update workflows
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/lint.yml
Labels: backport-request
