Repository nextcloud/privacy, pull requests merged in 2023-11, with the labels that each got.

#988 [master] Fix npm audit
  js/privacy-main.js
  js/privacy-main.js.map
  package-lock.json
Labels: dependencies, 3. to review

#992 enh(a11y): Make privacy markup accessible
  js/privacy-data_image_svg_xml_base64_PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCI-65943f.js
  js/privacy-main.js
  js/privacy-main.js.LICENSE.txt
  js/privacy-main.js.map
  js/privacy-node_modules_nextcloud_dialogs_dist_chunks_index-27e9ea0a_mjs.js
  js/privacy-node_modules_nextcloud_dialogs_dist_chunks_index-27e9ea0a_mjs.js.LICENSE.txt
  js/privacy-node_modules_nextcloud_dialogs_dist_chunks_index-27e9ea0a_mjs.js.map
  js/privacy-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-728d3f78_mjs.js
  js/privacy-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-728d3f78_mjs.js.LICENSE.txt
  lib/Settings/MissionSettings.php
  lib/Settings/WhoHasAccessSettings.php
  package-lock.json
  package.json
  src/components/AdminAccess.vue
  src/components/Admins.vue
  src/components/Encryption.vue
  src/components/Location.vue
  src/components/Privacy.vue
  src/components/ShareAccess.vue
  src/components/Shares.vue
  src/css/privacy.scss
  src/env.d.ts
  src/main.js
  src/main.ts
  src/nameProvider.js
  src/views/Access.vue
  src/views/Location.vue
  src/views/Manifesto.vue
  src/views/Mission.vue
  templates/mission.php
  templates/user-data-manifesto.php
  templates/where-is-your-data.php
  templates/who-has-access.php
  tsconfig.json
  webpack.js
Labels: enhancement, 4. to release, backport-request, accessibility

#998 [stable28] enh(a11y): Make privacy markup accessible
  js/privacy-data_image_svg_xml_base64_PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCI-65943f.js
  js/privacy-main.js
  js/privacy-main.js.LICENSE.txt
  js/privacy-main.js.map
  js/privacy-node_modules_nextcloud_dialogs_dist_chunks_index-27e9ea0a_mjs.js
  js/privacy-node_modules_nextcloud_dialogs_dist_chunks_index-27e9ea0a_mjs.js.LICENSE.txt
  js/privacy-node_modules_nextcloud_dialogs_dist_chunks_index-27e9ea0a_mjs.js.map
  js/privacy-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-728d3f78_mjs.js
  js/privacy-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-728d3f78_mjs.js.LICENSE.txt
  lib/Settings/MissionSettings.php
  lib/Settings/WhoHasAccessSettings.php
  package-lock.json
  package.json
  src/components/AdminAccess.vue
  src/components/Admins.vue
  src/components/Encryption.vue
  src/components/Location.vue
  src/components/Privacy.vue
  src/components/ShareAccess.vue
  src/components/Shares.vue
  src/css/privacy.scss
  src/env.d.ts
  src/main.js
  src/main.ts
  src/nameProvider.js
  src/views/Access.vue
  src/views/Location.vue
  src/views/Manifesto.vue
  src/views/Mission.vue
  templates/mission.php
  templates/user-data-manifesto.php
  templates/where-is-your-data.php
  templates/who-has-access.php
  tsconfig.json
  webpack.js
Labels: 4. to release, accessibility
