Repository nextcloud/privacy, pull requests merged in 2023-07, with the labels that each got.

#924 [stable26] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#923 [stable25] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#922 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#921 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#928 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#930 [stable26] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#931 Create pr-feedback.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#926 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#938 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#927 [stable25] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#937 [stable26] Fix npm audit
  .github/workflows/fixup.yml
  package-lock.json
Labels: dependencies, 3. to review

#912 chore: update node engines to next LTS
  package.json
Labels: dependencies, 3. to review, automated
