Repository nextcloud/privacy, pull requests merged in 2023-06, with the labels that each got.

#900 chore: update workflows from templates
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
Labels: dependencies, 3. to review, automated

#905 [stable26] Fix npm audit
  js/privacy-main.js
  js/privacy-main.js.map
  package-lock.json
Labels: dependencies, 3. to review

#904 [master] Fix npm audit
  js/privacy-main.js
  js/privacy-main.js.map
  package-lock.json
Labels: dependencies, 3. to review

#907 [stable25] Fix npm audit
  js/privacy-main.js
  js/privacy-main.js.map
  package-lock.json
Labels: dependencies, 3. to review

#906 [stable27] Fix npm audit
  js/privacy-main.js
  js/privacy-main.js.map
  package-lock.json
Labels: dependencies, 3. to review, 4. to release

#893 chore(CI): Adjust testing matrix for Nextcloud 27 on stable27
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
Labels: 4. to release

#919 [stable26] Fix npm audit
  js/privacy-main.js
  js/privacy-main.js.map
  package-lock.json
Labels: dependencies, 3. to review

#918 [master] Fix npm audit
  js/privacy-main.js
  js/privacy-main.js.map
  package-lock.json
Labels: dependencies, 3. to review

#917 [stable25] Fix npm audit
  js/privacy-main.js
  js/privacy-main.js.map
  package-lock.json
Labels: dependencies, 3. to review
