Repository nextcloud/privacy, pull requests merged in 2023-05, with the labels that each got.

#885 Add npm-audit-fix
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#886 [stable25] Fix npm audit
  js/privacy-main.js
  js/privacy-main.js.map
  package-lock.json
Labels: dependencies, 3. to review

#888 [stable26] Fix npm audit
  js/privacy-main.js
  js/privacy-main.js.map
  package-lock.json
Labels: dependencies, 3. to review

#892 Use the color-primary-element* variables
  js/privacy-main.js
  js/privacy-main.js.map
  src/components/Location.vue
Labels: bug, 3. to review, design

#899 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
