Repository nextcloud/privacy, pull requests merged in 2024-01, with the labels that each got.

#999 fix(i18n): Fixed syntax
  js/privacy-main.js
  js/privacy-main.js.map
  src/components/ShareAccess.vue
Labels: feedback-requested

#1006 [stable28] chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
Labels: dependencies, 3. to review, automated

#1014 [stable26] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1015 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1016 Update npm and node engines versions
  package.json
Labels: dependencies

#1019 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
